Nsl_Core/Nsl_Core/Models/EFModels/Comments.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class Comments
    {
        public int Id { get; set; }
        public int? MemberTutorRecordId { get; set; }
        public string CommentContent { get; set; }
        public double? Satisfaction { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }

        public virtual MembersTutorRecords MemberTutorRecord { get; set; }
    }
}

Nsl_Core/Nsl_Core/Controllers/Back/BackTeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Nsl_Core.Models;
using Nsl_Core.Models.Infra.Repositories.DapperRepositories;
using Nsl_Core.Models.EFModels;
using Nsl_Core.Models.Infra.Repositories.EFRepositories;
using Nsl_Core.Models.Interfaces;
using Microsoft.EntityFrameworkCore;
using Nsl_Core.Models.Dtos;
using NSL_html.Models.Infra;
using Nsl_Core.Models.Infra;
using Nsl_Core.Models.Dtos.Teacher.TeacherResume;

namespace NSL_html.Controllers.Back
{
    public class BackTeacherController : Controller
    {
        private readonly NSL_DBContext _db;
        private readonly IWebHostEnvironment _host;
        private readonly IConfiguration _configuration;
        public BackTeacherController(NSL_DBContext db, IWebHostEnvironment host, IConfiguration configuration)
        {
            _db = db;
            _host = host;
            _configuration = configuration;
        }


        [HttpPost]//接受view傳過來會員資料進行修改
        public IActionResult Verify(int teacherId)
        {
            ITeacherRepo repo = new TeacherRepositoryEF(_db);
            try
            {
                var tMemberInfo = repo.Update(teacherId);
                EmailHelper.VerifyTeacher(tMemberInfo);
                repo.CreateResume(teacherId);
			}
            catch(ArgumentNullException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("ApplyList");
 
        }
        public IActionResult ApplyList()
        {
            return View();
		}

        public IActionResult CAU(int id)
        {
            var repo = new TeacherRepositoriesDapper(_configuration);
            var dto=repo.GetBackTeacherResume(id);

            return View(dto);
        }

        public IActionResult Application(int id)
        {
            var repo = new TeacherRepositoriesDapper(_configuration);
            var dto = repo.GetApply(id);
            return View(dto);
        }

        public IActionResult Comment(int id)
        {
            var repo = new TeacherRepositoriesDapper(_configuration);
            var dto = repo.GetBackTeacherResume(id);

            return View(dto);
        }

        //public IActionResult GetComment(int id)
        //{
        //    var repo = new TeacherRecordRepo(_configuration);
        //    var dto = repo.GetComments(id);
        //    return Json(dto);
        //}

		public IActionResult ResumeList()
		{
            return View();
		}
	}
}

Nsl_Core/Nsl_Core/Views/BackTeacher/Application.cshtml
@{
	ViewData["Title"] = "TeacherApplication";
	Layout = "~/Views/Shared/_BackLayout.cshtml";
}
@model Nsl_Core.Models.Dtos.Teacher.TeacherApply.TeacherApplyDto
<section>
	<div class="backplatform-page">
		<!-- navbar -->
		<div class="open-sidenav-btn" id="navbarOpen">
			&#9776;
		</div>

		<div class="backplatform-main">
			<div class="backplatform-title">
				<h2 id="backTitle">教師資料維護</h2>
			</div>

		</div>
		<hr />
		<div class="container wow fadeInUp">
			<p class="font30px text-center">申請內容</p>
			<div id="applyList"class="row align-items-center">
				<div class="col-md-7 col-lg-7 mb-30 wow fadeInUp" data-wow-duration="600ms">
					<div class="container text-center mt-3">
						<form>
							<div class="font20px">

								<div class="row my-1">
									<div class="col-6 text-right">
										<label class="me-2">姓名：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.TeacherName</label>
									</div>
								</div>

								<div class="row my-1">
									<div class="col-6 text-right">
										<label class="me-2">主要教學語言：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.CategoryName</label>
									</div>
								</div>

								<div class="row my-1">
									<div class="col-6 text-right">
										<label class="me-2">可溝通語言：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.LanguageName</label>
									</div>
								</div>

								<div class="row my-1">
									<div class="col-6 text-right">
										<label class="me-2">教學經驗：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.TutorExperienceName</label>
									</div>
								</div>

								<div class="row my-2">
									<div class="col-6 text-right">
										<label class="me-2">工作狀態：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.WorkStatusName</label>
									</div>
								</div>

								<div class="row my-2">
									<div class="col-6 text-right">
										<label class="me-2">一周可教學時間：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.TutorHoursOfWeekName</label>
									</div>
								</div>

								<div class="row my-2">
									<div class="col-6 text-right">
										<label class="me-2">月收入目標：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<label class="me-2 span-coloronly">@Model.RevenueTargetName</label>
									</div>
								</div>

								<div class="row my-2">
									<div class="col-6 text-right">
										<label class="me-2">簡短自介：</label>
									</div>
									<div class="col-6 div-backcoupon text-start">
										<textarea class="form-control" name="textarea" placeholder="請輸入內文"
												  style="height:150px;display: inline-block; width:70%" readonly>@Model.Intro</textarea>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				<div class="col-5 div-backteacherCAU">
					<img src="~/uploads/@Model.ImageName" alt="members" class="pic-backmemberCAU">
				</div>
				<div class="mt-4 ms-2 row text-center justify-content-center">
					<div class="mx-auto px-3 display-inline">
						<a href="~/BackTeacher/ApplyList" class="btn btn-primary">回上一頁</a>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</section>
@section Scripts{
	<script>
		const url = "https://localhost:7016/api/TeachersApplies/GetApply"

		const ulTeacher = $("#applyList");

		//teacherApply()
		
		//async function teacherApply() {
		//	const response = await fetch(url + "?teacherId=" + @Model.Id)
		//	const datas = await response.json();
		//	console.log(datas)
		//	const teacherApply = datas.map(teacher => {
		//		let string = `				<div class="col-md-7 col-lg-7 mb-30 wow fadeInUp" data-wow-duration="600ms">
		//					<div class="container text-center mt-3">
		//						<form>
		//							<div class="font20px">

		//								<div class="row my-1">
		//									<div class="col-6 text-right">
		//										<label class="me-2">姓名：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">Jennie</label>
		//									</div>
		//								</div>

		//								<div class="row my-1">
		//									<div class="col-6 text-right">
		//										<label class="me-2">主要教學語言：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">英文</label>
		//									</div>
		//								</div>

		//								<div class="row my-1">
		//									<div class="col-6 text-right">
		//										<label class="me-2">可溝通語言：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">英文、中文、日文</label>
		//									</div>
		//								</div>

		//								<div class="row my-1">
		//									<div class="col-6 text-right">
		//										<label class="me-2">教學經驗：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">曾有3年面對面教學經驗</label>
		//									</div>
		//								</div>

		//								<div class="row my-2">
		//									<div class="col-6 text-right">
		//										<label class="me-2">工作狀態：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">我有其他兼職工作</label>
		//									</div>
		//								</div>

		//								<div class="row my-2">
		//									<div class="col-6 text-right">
		//										<label class="me-2">一周可教學時間：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">25~35 小時</label>
		//									</div>
		//								</div>

		//								<div class="row my-2">
		//									<div class="col-6 text-right">
		//										<label class="me-2">月收入目標：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<label class="me-2 span-coloronly">NT$90000~NT$135000</label>
		//									</div>
		//								</div>

		//								<div class="row my-2">
		//									<div class="col-6 text-right">
		//										<label class="me-2">簡短自介：</label>
		//									</div>
		//									<div class="col-6 div-backcoupon text-start">
		//										<textarea class="form-control" name="textarea" placeholder="請輸入內文"
		//												  style="height:150px;display: inline-block; width:70%" readonly>你好我是誰誰誰，有3年家教經驗，主教英文</textarea>
		//									</div>
		//								</div>
		//							</div>
		//						</form>
		//					</div>
		//				</div>
		//				<div class="col-5 div-backteacherCAU">
		//					<img src='@Url.Content("~/uploads/")${teacher.ImageName}' alt="members" class="pic-backmemberCAU">
		//				</div>
		//				<div class="mt-4 ms-2 row text-center justify-content-center">
		//					<div class="mx-auto px-3 display-inline">
		//						<button type="submit" class="btn btn-primary">確定</button>

		//						<a href="~/BackTeacher/ApplyList" class="btn btn-primary"
		//						   style="margin-left: 10%;">回上一頁</a>
		//					</div>
		//				</div>`
		//		return (string)
		//	})
		//	ulTeacher.html(teacherApply.join(""))
		//}
	</script>
}

Nsl_Core/Nsl_Core/Views/BackTeacher/ApplyList.cshtml
@{
    ViewData["Title"] = "ApplyList";
    Layout = "~/Views/Shared/_BackLayout.cshtml";
}
@model Nsl_Core.Models.Dtos.Teacher.TeacherApply.TeacherApplyDto
<!-- Title -->
<section>
    <div class="backplatform-page">
        <!-- navbar -->
        <div class="open-sidenav-btn" id="navbarOpen">
            &#9776;
        </div>

        <div class="backplatform-main">
            <div class="backplatform-title">
                <h2 id="backTitle">教師資料維護</h2>
            </div>

        </div>
        <hr />

        <div class="container">
            <div class="row">
                <div class="col-7 ul-reset">
                    <form>
                        <input type="text" id="searchText" placeholder="請輸入要搜尋的關鍵字(姓名)" class="form-control d-inline-block" style="width:60%" />
                        <button type="button" id="searchApply"
                                class="btn-backedit margin-RL">
                            搜尋
                        </button>
                        <button id="showAll" type="button" class="btn-backedit">顯示全部</button>
                    </form>
                </div>
                <div class="col-5 padding-reset ps-5 pe-0 position-relative">
                    <span class="span-backmember ">搜尋語言：</span>
                    <select id="selectLan" name="selectLan" class="form-control div-login-form-input position-absolute end-0 mt-1">
                        <option class="optionVal">請選擇</option>
                    </select>
                </div>
            </div>
            @*分頁*@
            <nav aria-label="Page navigation example" class="margin-center d-inline">
                <ul class="pagination d-flex" style="padding-left:40%">
                    <li class="page-item pages">
                        <a class="page-link" href="#" aria-label="Previous" onclick="PagePrevious()">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next" onclick="PageNext()">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="teachers-list">
                <ul class="ul-reset wow fadeInUp">
                    <li id="applyList">
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/js/pagination.js"></script>
    <script>
        const url = "https://localhost:7016/api/TeachersApplies/GetAllApplyList"
        const url2 = "https://localhost:7016/api/TeachersApplies"
        const url3 = "https://localhost:7016/api/Others/Categories"

        const ulTeacher = $("#applyList");
        Load();
        //自行指定
        range=10

        async function Load() {
            const response = await fetch(url);
            const datas = await response.json();
            const teachers = teacherApplyList(datas);
            ulTeacher.html(teachers.join(""))
            checkStatus()
            applyDelEvent();
            LoadselectLan();
            PageItem(datas) //Load的時候要渲染控制器
        }
        function teacherApplyList(datas) {
            //獲得到的陣列要經過下面兩步驟串接,陣列長度要無條件進位
            arrLenght = (Math.floor(datas.length))+1
            pagination = Pagination(datas)
            //依照原本步驟將pagination渲染出去
            const teacherApply = pagination.map(teacher => {
                let teacherIntro = teacher.intro !== null ? teacher.intro : "";
                const verifyHtml = (teacher.statusName === "已審核") ?
                                    `<button type="button" class="btn-backedit2 checkStatus" value="${teacher.id}" disabled="disabled" style="background-color:#cecece"> 驗證 </button>` :
                                    `<button type="button" class="btn-backedit2 checkStatus" value="${teacher.id}"> 驗證 </button>`

                let string = `<div class="div-backmember row ani-backcolor">
                                        <div class="col-2 px-0">
                                           <div class="div-triangle-number">
                                              <span class="span-triangle-number">${teacher.id}</span>
                                           </div>
                                           <div class="div-circle mb-4">
                                              <img class="pic-backmember" src='@Url.Content("~/uploads/")${teacher.imageName}' alt="teacher" title="teacherName"/>
                                           </div>
                                          </div>
                                          <div class="col-8 div-backmemberde">
                                              <div>
                                                <p id="teacherName" class="p-backmember display-inline">${teacher.teacherName}</p>
                                                <span class="span-backmember">${teacherIntro}</span>
                                              </div>
                                              <div>
                                                <span class="span-backmember">語言類別：</span>
                                                <span class="span-backmember">${teacher.categoryName}</span>
                                              </div>
                                              <div>
                                                <span class="span-backmember">審核狀態：</span>
                                                <span class="span-backmember">${teacher.statusName}</span>
                                              </div>
                                            </div>
                                          <div class="col-2">
                                            <form>
                                              <a href='@Url.Content("~/BackTeacher/Application/")${teacher.id}' class="btn-backedit2">查看申請</a>
                                                     ${verifyHtml}
                                              <button type="button" class="btn-backedit2 deleteApply" value="${teacher.id}">刪除</button>
                                            </form>
                                          </div>
                                        </div>`
                return (string)
            })
            return teacherApply;

        }

        $("#showAll").on("click", async (e) => {
            ulTeacher.empty();
            Load();
            applyDelEvent();
            checkStatus()
        })

        function checkStatus() {
            $(".checkStatus").on("click", function () {
                const button = $(this); 
                const id = button.val();

                Swal.fire({
                    title: '確定要審核通過嗎?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '確定',
                    cancelButtonText: '取消'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: `@Url.Action("Verify", "BackTeacher")?teacherId=${id}`,
                            type: 'POST',
                            success: function (result) {
                                Swal.fire('信件已寄出', "此老師已驗證", "success");
                                ulTeacher.empty();
                                Load();
                            },
                            error: function () {
                                Swal.fire('提示', "此老師已是審核狀態", "error");
                            }
                        });
                    }
                });
            });
        }

        $("#searchApply").on("click", async (e) => {
            ulTeacher.empty();
            const response = await fetch(url + "?search=" + $("#searchText").val())
            const datas = await response.json();
            const teachers = teacherApplyList(datas);
            ulTeacher.html(teachers.join(""))
            applyDelEvent()
            checkStatus()
        })

        $("#selectLan").on("change", async (e) => {
            ulTeacher.empty();
            if ($(".optionText:selected").val() == undefined) {
                load()
            }
            const response = await fetch(url + "?searchLan=" + $(".optionText:selected").val())
            const datas = await response.json();
            const teachers = teacherApplyList(datas);
            ulTeacher.html(teachers.join(""))
            applyDelEvent()
            checkStatus()
        })

        const selectLan = document.querySelector('#selectLan');
        async function LoadselectLan() {
            const response = await fetch(url3);
            const datas = await response.json();
            const categories = datas.map(category => {
                return (`<option class="optionText" value="${category.id}">${category.name}</option>`)
            })
            selectLan.innerHTML = "<option>請選擇語言</option>" + categories.join("");
        }

        function applyDelEvent() {
            $(".deleteApply").on("click", function () {
                const id = $(this).val();

                Swal.fire({
                    title: '確定要刪除嗎?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: '確定',
                    cancelButtonText: '取消'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: "https://localhost:7016/api/TeachersApplies/DeleteApply" + "?teacherId=" + id,
                            type: 'DELETE'
                        }).done(function (data) {
                            if (data.isSuccess) {
                                Swal.fire({
                                    icon: 'success',
                                    title: '刪除成功！',
                                    text: "編號為 " + id + " 的申請已成功刪除。"
                                }).then((innerResult) => {
                                    if (innerResult.isConfirmed) {
                                        Load();
                                    }
                                });
                            } else {
                                Swal.fire({
                                    icon: 'error',
                                    title: '刪除失敗！',
                                    text: data.errMsg || '刪除過程中發生了錯誤。'
                                });
                            }
                        }).fail(function () {
                            Swal.fire({
                                icon: 'error',
                                title: '刪除失敗！',
                                text: "無法刪除編號為 " + id + " 的申請。"
                            });
                        });
                    }
                });
            });
        }

    </script>
}

Nsl_Core/Nsl_Core/Views/BackTeacher/CAU.cshtml
@{
    ViewData["Title"] = "CAU";
    Layout = "~/Views/Shared/_BackLayout.cshtml";
}
@model Nsl_Core.Models.Dtos.Teacher.TeacherResume.BackTeacherResumeDto
<!-- Title -->
<section>
    <div class="backplatform-page">
        <!-- navbar -->
        <div class="open-sidenav-btn" id="navbarOpen">
            &#9776;
        </div>

        <div class="backplatform-main">
            <div class="backplatform-title">
                <h2 id="backTitle">教師資料維護</h2>
            </div>

        </div>
        <hr />
        <div class="container wow fadeInUp">
            <p class="font30px text-center">基本資料</p>
            <div class="row align-items-center">
                <div class="col-md-7 col-lg-7 mb-30 wow fadeInUp" data-wow-duration="600ms">
                    <div class="container text-center mt-3">
                        <form>
                            <div class="font20px">

                                <div class="row my-1">
                                    <div class="col-6 text-right">
                                        <label class="me-2">姓名：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <label class="me-2 span-coloronly">@Model.Name</label>
                                    </div>
                                </div>

                                <div class="row my-1">
                                    <div class="col-6 text-right">
                                        <label class="me-2">已完成課堂數：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <label class="me-2 span-coloronly">@Model.FinishCount</label>
                                    </div>
                                </div>

                                <div class="row my-1">
                                    <div class="col-6 text-right">
                                        <label class="me-2">未完成課堂數：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <label class="me-2 span-coloronly">@Model.UnfinishedCount</label>
                                    </div>
                                </div>

                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2" style="margin-top:10px">課程滿意度：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start" style="display: flex; align-items: center;">
                                        <label class="me-2 span-coloronly">@string.Format("{0:N1}", Model.Satisfaction)</label>
                                        <a href='@Url.Content("~/BackTeacher/Comment/")@Model.TeacherId' name="TeacherId" class="btn-backedit2" style="font-size:16px;">評論維護</a>
                                    </div>
                                </div>
                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">銀行代碼：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <input type="text" class="form-control div-login-form-input"
                                               id="bankAccount" readonly value="@Model.BankCodeName" />
                                    </div>
                                </div>

                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">銀行帳號：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <input type="text" class="form-control div-login-form-input"
                                               id="bankAccount" readonly value="@Model.BankAccount" />
                                    </div>
                                </div>
                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">課程收費(NT$/小時)：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        @{
                                            int? priceIntegerPart = (int?)Model.Price;
                                        }
                                        <input type="text" class="form-control div-login-form-input"
                                               id="price" readonly value="@((priceIntegerPart.HasValue) ? priceIntegerPart.Value.ToString("N0") : string.Empty)" />
                                    </div>
                                </div>

                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">工作經驗：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <input type="text" class="form-control div-login-form-input"
                                               id="experience" readonly value="@Model.WorkExperience" />
                                    </div>
                                </div>

                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">Email：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <input type="text" class="form-control div-login-form-input"
                                               id="email" readonly value="@Model.Email" />
                                    </div>
                                </div>

                                <div class="row my-2">
                                    <div class="col-6 text-right">
                                        <label class="me-2">電話號碼：</label>
                                    </div>
                                    <div class="col-6 div-backcoupon text-start">
                                        <input type="text" class="form-control div-login-form-input"
                                               id="phone" readonly value="@Model.Phone" />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-5 div-backteacherCAU" style="border-radius:10%">
                    <img src="~/uploads/@Model.ImageName" alt="members" class="pic-backmemberCAU">
                </div>
                <hr class="col-12 mt-3">

                <div class="col-4"></div>
                <div class="mt-4 ms-2 col-4">
                    <div class="mx-auto px-3 display-inline">
                        <a href=@Url.Content("~/BackTeacher/ResumeList") class="btn btn-primary"
                           style="margin-left: 30%;">回上一頁</a>
                    </div>
                </div>
                <div class="col-4"></div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script>

    </script>
}

Nsl_Core/Nsl_Core/Views/BackTeacher/_TutorRecordPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@